//首页mutations
export const INIT_SWIPE = 'INIT_SWIPE'

export const INIT_CATEGORY = 'INIT_CATEGORY'

export const INIT_PRODUCT_LIST = 'INIT_PRODUCT_LIST'

export const LOAD_MORE_PRODUCT = 'LOAD_MORE_PRODUCT'

export const HAS_MORE_PRODUCT = 'HAS_MORE_PRODUCT'

//购物车mutations
export const SWITCH_PRODUCT_IN_CART = 'SWITCH_PRODUCT_IN_CART'

export const DELETE_PRODUCT_IN_CART = 'DELETE_PRODUCT_IN_CART'

export const LOGING_REFRESH_CART = 'LOGING_REFRESH_CART'

export const SWITCH_PRODUCT_STATE = 'SWITCH_PRODUCT_STATE'

//产品详情页
export const INIT_PRODUCT_DETAIL = 'INIT_PRODUCT_DETAIL'

//用户中心
export const INIT_LOGING_USER = 'INIT_LOGING_USER'

export const USER_LOGOUT_ACTION = 'USER_LOGOUT_ACTION'

export const BIND_TEL_FLAG = 'BIND_TEL_FLAG'

//订单列表
export const INIT_ORDER_LIST = 'INIT_ORDER_LIST'

export const SWITCH_ORDER_TYPE = 'SWITCH_ORDER_TYPE'

//清除订单列表
export const CLEAR_ORDER_LIST = 'CLEAR_ORDER_LIST'

//购物车选中结算
export const SELECT_PRODUCT_INDEX = 'SELECT_PRODUCT_INDEX'

//搜索保存
export const SWITCH_SEARCH_RESULT = 'SWITCH_SEARCH_RESULT'

export const SWITCH_SEARCH_KEYWORD = 'SWITCH_SEARCH_KEYWORD'

//办理押金状态保存
export const DEPOSIT_ORDER_INFO = 'DEPOSIT_ORDER_INFO'

export const CLEAR_DEPOSIT_INFO = 'CLEAR_DEPOSIT_INFO'